#! /usr/bin/env python
# encoding: utf-8

def build(bld):
  directories = ['']
  bld.recurse(directories)

  bld(features = 'cxx',
      source   = 'gtest_main.cc',
      use      = 'GTEST',
      target   = 'unittestmain')
